# Generated by Django 5.0.2 on 2025-06-14 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_service', '0002_initial'),
        ('vet_service', '__first__'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha', '-hora_inicio'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='fecha_actualizacion',
            new_name='ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No Show')], default='programada', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta General'), ('vacunacion', 'Vacunación'), ('cirugia', 'Cirugía'), ('emergencia', 'Emergencia'), ('control', 'Control'), ('grooming', 'Peluquería')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet_service.veterinario'),
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('medicamentos', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('proxima_cita', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment_service.cita')),
            ],
            options={
                'verbose_name': 'Historial Médico',
                'verbose_name_plural': 'Historiales Médicos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
