# Generated by Django 5.0.2 on 2025-06-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='direccion_propietario',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono_propietario',
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
